name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style-check:
    name: Format (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install
        run: npm ci

      - name: Check Format
        run: npx prettier . --check

  eslint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install
        run: npm ci

      - name: ESLint
        run: npx eslint .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
